### ISSUE TITLE
2GB memory limit

### ISSUE THREAD

**Issue by Dromen** [spotnet/spotnet#35] opened 2015-04-08 12:48 UTC
The 2 GB memory limit causes problems with Spotnet 1.8.1.

The solution is to retrieve the data in separate batches of 100.000 spots/comments.

**Comment by mesa57** [comment] 2015-04-08 13:27
Solution was clear. Already got it working on branch 1.8.1. But I have start all over again on the current branch.

**Comment by poes** [comment] 2015-04-08 13:39
The solution is not so clear, because the order in which spots are processed needs to stay the same in order for moderation to work. Also its much less efficient to delete spots that were already committed to the database, so performance will suffer too.

And the refactored code is identical to the 1.8.1 branch, only locations of files have changed.

**Comment by mesa57** [comment] 2015-04-08 14:14
I agree that spots always should be processed from old to new for moderation to work (otherwise you could get a moderation message for a spot not yet retrieved). Of cause assuming the moderation message do to point to 'future' spots. Current version commits to the database before deleting, but performance can be greatly increased by adding an index on msgid. Later I would like to add deletion of the spots in the cache.

**Comment by poes** [comment] 2015-04-09 08:06
Adding an index on message-id makes deleting moderated spots faster, but it also makes inserting normal spots slower. And since only a small percentage of the spots are moderated, I think the index will increase the total retrieval time instead of shorten it. But feel free to proof me wrong.

The current code already deletes spots from cache (actually, technically it doesn't delete them, it just never adds them), so spots that were moderated and retrieved in the same operation are never committed to the database.

**Comment by mesa57** [comment] 2015-04-09 10:04
Thanks for pointing out that moderated spots are never added to the cache. I will make sure that code keeps working. Btw. I don't know if you noticed, but moderation is pretty have today. There are also some mod-bots running and many mod messages are duplicate. 
I noticed that gathering spots spends the most time in deleting moderated spots. 
SQLite does not add much overhead for inserting in an index, but is pretty bad when deletion has to do a table scan. So overall time gets much better.

**Comment by mesa57** [comment] 2015-04-10 08:37
Found in in addspots function (didn't expect it there). Also nice that the list of deletes is a hashset (no duplicates). 
Question : do you know why threads are nested (on completion of one thread it starts the next). This seems to be needless complex, 1 thread would suffice to get status updates of the mainthread working ? But maybe I am missing something ?

**Comment by poes** [comment] 2015-04-10 16:21
It was done in the AddSpots function because the list of delete-ids is shared between all batches, and not just for the current batch of spots.

The complexity of the workers is because it was originally ment to be multithreaded, until that turned out to be too much work, and the multithreading was disabled.

You can rewrite as much as you want as long as you are careful not to break anything. The simplest approach would be to abort the task after you have X spots, and restart the task in status.xaml until it returns 0 new spots/comments. That way only a few changes are needed.

**Comment by mesa57** [comment] 2015-04-10 16:33
That's exactly how I've done it now. I left the thread code untouched as much as possible. Works like a charm :) Only thing I have to do now is give back the correct counters to the mainthread (it now gets the counters from the last batch) and do a regression test with the previous version. I will try refactoring of the threads in a next release. Multithreading can be usefull in fetching the headers from the provider (if more then 1 connection is allowed) and processing the retrieved headers. Multithreading database updates only slows things down I discovered.

**Comment by mesa57** [comment] 2015-04-12 08:51
Help ! I tried to add extra attributes to settings (max headers to download) and visual studio instantly creates new settings, gives errors that my.settings cannot be found anymore. It forces to save the settings under the My Project folder instead of the original Resources folder. Do you know how to correct this ?

**Comment by poes** [comment] 2015-04-12 10:14
I had the same problem with VS2015, seems the 'My project' folder has become a requirement, so just move your stuff to there.

**Comment by mesa57** [comment] 2015-04-12 16:12
Installed VS2015 now. Could you open the screens (mainwindow) ? If I try VS2015 immediatly crashes ... :(

**Closed** 2022-02-17 20:37 UTC
